### PR TITLE
*: update to kubo v0.18.1

### LINKED ISSUE #59: Build/Release GH action needs to be updated for new docker image
See https://github.com/trudi-group/ipfs-metric-exporter/actions/runs/4053827582
and https://github.com/trudi-group/ipfs-metric-exporter/blob/master/.github/workflows/Build_release.yaml#L16

### PR DESCRIPTION
**Pull request by mrd0ll4r**
Fixes #59

### CODE REVIEW

**Comment by mg98** [comment]
To have the Docker image as package release, check how I did it on [my master branch](https://github.com/mg98/ipfs-metric-exporter/blob/master/.github/workflows/Build_release.yaml). Sorry, my bad that I didn't have it on the PR...

**Comment by mrd0ll4r** [comment]
What about now? I still need the two binaries, but hopefully it'll also publish the container? What's gonna be the version tag, I wonder?

**Comment by mg98** [comment]
> What about now? I still need the two binaries, but hopefully it'll also publish the container? What's gonna be the version tag, I wonder?
> 
> EDIT: Ah, just `latest` I guess

LGTM.

Side note: I think we could save on one image build time by tagging the image in `Makefile:35` `trudi-group/kubo-mexport:latest` and putting `make gen-out` before the `push-to-ghcr` action ([they build with `--cache-from`](https://github.com/macbre/push-to-ghcr/blob/master/action.yml#LL94C11-L94C25)). But yeah, not important.

**Comment by mrd0ll4r** [comment]
I think it tags `:latest` automatically if unspecified (at least on my machine). But I changed the order, why not save some resources :)

**Pull request merged**
